name: Publish Docker image to Docker Hub

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: [main]
    types: 
      - completed
    
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: izm1chael/viper-web:latest
