name: Vulnerability Scan

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual Run'
        required: true

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker image
        run: docker pull izm1chael/viper-web:latest
      - uses: dataswift/gha-trivy@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: docker.pkg.github.com/izm1chael/viper-web-docker/viper-web:latest
